import dotenv from "dotenv";

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI!;
const SALT = Number(process.env.SALT!);
const JWT_SECRET = process.env.JWT_SECRET!;
const SECRET = new TextEncoder().encode(JWT_SECRET);
const ACCESS_TOKEN_NAME = "accessToken";
const REFRESH_TOKEN_NAME = "refreshToken";
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY!;
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY!;
const ACCESS_TOKEN_COOKIE_EXPIRY = 15 * 60 * 1000;
const REFRESH_TOKEN_COOKIE_EXPIRY = 7 * 24 * 60 * 60 * 1000;
const VERIFICATION_TOKEN_EXPIRY = 24 * 60 * 60 * 1000;
const RESET_PASSWORD_TOKEN_EXPIRY = 60 * 60 * 1000;

export {
  MONGODB_URI,
  SALT,
  JWT_SECRET,
  SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  ACCESS_TOKEN_COOKIE_EXPIRY,
  REFRESH_TOKEN_COOKIE_EXPIRY,
  ACCESS_TOKEN_NAME,
  REFRESH_TOKEN_NAME,
  VERIFICATION_TOKEN_EXPIRY,
  RESET_PASSWORD_TOKEN_EXPIRY,
};
